- hosts: 192.168.33.10
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure Python modules
      apt:
        name: python-apt

    - name: add nodejs ppa
      apt_repository:
        repo: ppa:chris-lea/node.js

    - name: install nodejs package
      apt:
        name: nodejs
